# Generated by Django 3.0.2 on 2020-02-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('address', models.CharField(default='', max_length=200)),
                ('contact', models.IntegerField()),
                ('collected_date', models.DateTimeField(auto_now_add=True)),
                ('tested', models.BooleanField(default=False)),
                ('test_category', models.ManyToManyField(blank=True, related_name='patient', to='medical_lab.TestCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('patient', models.ManyToManyField(blank=True, related_name='doctor', to='medical_lab.Patient')),
            ],
        ),
    ]
